export declare const PRODUCT_ROLES: string[];
export declare const PRODUCT_PERSONAS: string[];
export declare const PRODUCT_INTEGRATIONS: string[];
export declare const PRODUCT_ANALYTICS: string[];
export declare const PRODUCT_KPIS: string[];
export declare const PRODUCT_WORKFLOWS: string[];
export declare const PRODUCT_ONBOARDING: string[];
export declare const PRODUCT_GUARDS: string[];
export declare const PRODUCT_EXPANSION: string[];
export declare const PRODUCT_DATA_MODEL: string[];
export declare const PRODUCT_SUCCESS_SIGNALS: string[];
export declare function createProductSaasBlueprint(config: any, domain: any): {
    product: any;
    northStar: any;
    roles: string[];
    personas: string[];
    integrations: string[];
    analytics: string[];
    kpis: string[];
    workflows: string[];
    onboarding: string[];
    guards: string[];
    expansion: string[];
    dataModel: string[];
    successSignals: string[];
    modules: any;
    artifacts: any;
};
